language: python
python:
- '3.6'
script: pytest
deploy:
  provider: pypi
  user: foolcage
  password:
    secure: P3Kco9rUxd75FfnwxnqKwa9PhPMkk7J7zSs2ll0emI8T029G9u/RzdbBu6x0lYSPLNA2eXXYpodaxbKeac2q2JvZj2Dp07Xn71BYu1CKbJowGdngG+kkm0FCeWxMZ91XhxUerUSb25pJyr10h/0OJH/bZ+w4wqOVCRMNUCndROFuI72tkPcGA3lltyr3AtoeTam9FBnHDrhgLwoghVNlqn2ZUknsHZc7xNyj6HvTgh+qmztD7YxPkxFPRRO7zJFSMXx6tyTBJ4kHQ5gJdWg+sjHJkJFVdeyQEj6mrvEeZ3VZyz4BvVHLwyl3aAu4DNtXLhpcHJh9Gypt88mIXj06Rqg+PO/RExFecULuiS8f5oVzqLBpfiwTsB11BeEeXNUc5aYjjad5thXvKWDOwksyLRnKZgFIp0oLZYREr4N3ezggBhWge0ZLL8PT3hFnCVZTVdGdVjJeKIDCIe2d0ZnPbWS4tYu+AJedS+XdCxcJR84YCJyGYgF21pyYiwfKMedjti6IbhbImTE3KaeiyCkjo1BfdDBLpdpw8kFwM6i3TLUAYVIx1X9h635gpnF2PV2ptmZk8jFCsTlwTY/9AWsSiRSc7yvrPFESK5MXFc++BlFGWDWPQmE8SRUwX5gVDuAjN+UY/QjgkucMhxoGjDTaTNbvkWL5q3rioWL6S7WfG5U=
  on:
    tags: true
